config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :zats, :artists, :studios

  devise_for :engineers, controllers: { omniauth_callbacks: 'engineers/omniauth_callbacks', registrations: 'registrations', sessions: 'engineers/sessions', sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
#devise_for :engineers, controllers: { sessions: 'engineers/sessions' }
 # resources :engineers #do
    #root 'zats#index' 
    get '/engineers/sign_out' => 'engineers/sessions#destroy'
#    get '/signout' => 'sessions#destroy'
  #  match '/engineers',   to: 'engineers#index',   via: 'get'
  #end
  #devise_for :engineers, :controllers => { :registrations => 'engineers' }

  #resources :engineers do
 #   resources :zats # , only: :create
  #end
  resources :artists do
    resources :zats # , only: :create
  end
  resources :studios do
    resources :zats # , only: :create
  end


  
end



  #resources :engineers
 #   get 'engineers', to: 'engineers#index', as: 'index'

  #  get 'zats/:id', to: 'zats#show', as: 'session'
  # get 'zats/index'
  #  devise_for :engineers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'zats/:id/edit', to: 'zats#edit', as: :edit_zat
  # patch 'zats/:id', to: 'zats#update'

  #  get 'studios/index'
  # get 'engineers/:id/zats/:zats_id'

  # resources :engineers do
  #   resources :zats
  #  end


   

app/models/artist.rb
class Artist < ApplicationRecord

 has_many :zats #adds methods to my model
          has_many :engineers, through: :zats
          has_many :studios, through: :zats



validates :name, presence: true, length: { minimum: 1 }
validates :name, uniqueness: true

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
    @zats = Zat.all
    @engineers = Engineer.all
    @studios = Studio.all
    #@artists = Artist.all


  end


def new
  @artist = Artist.new
end




  def edit
    @artist = Artist.find(params[:id])
 #   index
  end

def update
#    index
    @artist = Artist.find(params[:id])
    # raise params.inspect
    if @artist.update(params.require(:artist).permit(:artist_name))
      # binding.pry
      redirect_to artist_path(@artist)

    else
      render 'edit'
  end


end



def show
    index
    # binding.pry
    @artist = Artist.find(params[:id])
    #     redirect_to action: 'index'
    
  end



end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/views/artists/_edit_partial.html.erb
<!-- EDIT FORM -->
<%= form_for [@artist] do |p| %>

<h2>View Recording Artists</h2>
<h5>

    <label>Recording Artist:</label><br>
    <br>
    <br>
<input class="w3-input w3-padding-16" type="datetime-local" placeholder="Date and time" required name="date"
    value="2019-05-21T07:00">
    <%= p.submit %>
    <% end %>

    </p>

    </h4>
    <!-- END OF EDIT FORM -->


<%= link_to 'Delete Session', [@artist],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Recording Sessions', zats_path %>

app/views/artists/_new_partial.html.erb
<!-- USED in views/zats/index -->








<!-- EDIT FORM -->
    <!-- DISPLAY Erros message for STUDIO CREATION -->
        <input class="toggle-all" type="checkbox">
        <%if @artist.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@artist.errors.count, "error") %>
                prohibited this item from being saved:
                <% @artist.errors.full_messages.each do |msg| %>
            </h2>
            <ul style="list-style: none;">
                <li><div class="alert alert-danger"><%= msg %></div></li>
                <% end %>
            </ul>
            <%  end %>
    <!-- END OF EDIT FORM -->

app/views/artists/edit.html.erb
<h1>Artist#edit</h1>
<p>Find me in app/views/artist/edit.html.erb</p>



<body>
    <%= render 'edit_partial', form: @artist %>

    <!-- Last -->


    <!-- End page content -->

app/views/artists/index.html.erb
<h1>Artist#index</h1>
<p>Find me in app/views/artist/index.html.erb</p>
 <th>Location</th>

app/views/artists/show.html.erb
<body>

<!-- RECORDING SESSION INFO -->
<div>
<h2> Artist Information </h2>
<h3> Artist: <%= @artist.name.capitalize %></h3>
<br>

    <% if @artist.zats.blank? %>
    <h2>There are currently no recording sessions scheduled.</h2>
    <% else %>
    <h2>NoName's Scheduled Sessions</h1>
        <br>
    
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Session Date</th>
                    <th>Engineer</th>
                    <th>Studio</th>
                    <th>Complete</th>
                    <th>Cancel</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
    
            <% @artist.zats.each do |c| %>
            <tbody>
                <tr>
                    <td><a href="/engineers/@engineer_id page/:id"><%= c.id %></a></td>
                    <td><a href="/zats/:id/edit"><%= c.appointment_date.time.to_formatted_s(:rfc822) %></a></td>
                    <td><a href="/engineers/@engineer_id page/:id"><%= c.engineer.name.capitalize %></a></td>
                 
                    <td><a href="/studios/@studios_path"><%= c.studio.name.capitalize %></a></td>
                    <td><a href="/zats/:id/edit"><%= c.status %></a></td>
                    <td><a
                            href="/zats/@engineer_id"><%= link_to "Delete", c, method: :delete, data: { confirm: 'Are you sure you want to delete this recording session?' } %></a>
                    </td>
    
                </tr>
                <% end %>
            </tbody>
        </table>
    
        <p> <% end %> </p>
    


        <p> <%= link_to new_zat_path %> </p>
        <p> <%= link_to new_zat_path %> </p>
        <td><%= link_to @artist.name.capitalize, artist_path(@artist)%></td>

       
        <!-- END OF EDIT FORM -->