config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :zats, :artists, :studios

  devise_for :engineers, controllers: { omniauth_callbacks: 'engineers/omniauth_callbacks', registrations: 'registrations', sessions: 'engineers/sessions', sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
#devise_for :engineers, controllers: { sessions: 'engineers/sessions' }
 # resources :engineers #do
    #root 'zats#index' 
    get '/engineers/sign_out' => 'engineers/sessions#destroy'
#    get '/signout' => 'sessions#destroy'
  #  match '/engineers',   to: 'engineers#index',   via: 'get'
  #end
  #devise_for :engineers, :controllers => { :registrations => 'engineers' }

  #resources :engineers do
 #   resources :zats # , only: :create
  #end
  resources :artists do
    resources :zats # , only: :create
  end
  resources :studios do
    resources :zats # , only: :create
  end


  
end



  #resources :engineers
 #   get 'engineers', to: 'engineers#index', as: 'index'

  #  get 'zats/:id', to: 'zats#show', as: 'session'
  # get 'zats/index'
  #  devise_for :engineers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'zats/:id/edit', to: 'zats#edit', as: :edit_zat
  # patch 'zats/:id', to: 'zats#update'

  #  get 'studios/index'
  # get 'engineers/:id/zats/:zats_id'

  # resources :engineers do
  #   resources :zats
  #  end


   

app/models/zat.rb
class Zat < ApplicationRecord

  belongs_to :engineer
  belongs_to :artist
  belongs_to :studio

#scope :by_status, -> status  { where(status: status) if status.present? }
#scope :recent, -> { order("zats.updated_at DESC") }

scope :incomplete, -> { where(status: false)}
#scope :recent, -> { order("zats.updated_at DESC") }
# scope :appointment_date, -> { where(appointment_date: true) }
# scope :recent, -> { order("zats.appointment_date DESC") }


validates :engineer_id, presence: true, length: { minimum: 1 }
validates :artist_id, presence: true, length: { minimum: 1 }
validates :studio_id, presence: true, length: { minimum: 1 }

#use the validation below to ensure that an appointment/session date is entered
#validates :appointment_date, presence: true, length: { minimum: 1 }
#validates :appointment_date, uniqueness: true

STATUS = {
        :incomplete => 0,
        :complete => 1
    }
    #use hash above to set up key 10:00 v3
    #clearly define meaning of #0 || #1 in context


    
    def complete?
        self.status == STATUS[:complete]    
        #self.status == 1
    end

    def incomplete?
        self.status == STATUS[:incomplete]
        #self.status == 0
    end

    def complete!
        self.status = STATUS[:complete]
        self.save
        #self.status == 0
    end

    def incomplete!
        self.status = STATUS[:incomplete]
        self.save
        #self.status == 0
    end

def self.recent
    order("zats.updated_at DESC")
  end

#def self.incomplete
 #   where(complete: false)
    
#end


end

app/controllers/zats_controller.rb
# frozen_string_literal: true

class ZatsController < ApplicationController
http_basic_authenticate_with name: "lu", password: "password", except: [:index, :show]


  def index
    @engineers = Engineer.all
    @studios = Studio.all
    @artists = Artist.all
    if params[:artist_id]
      @zats = Artist.find(params[:artist_id]).zats
    elsif params[:engineer_id]
      @zats = Engineer.find(params[:engineer_id]).zats
    elsif params[:studio_id]
      @zats = Studio.find(params[:studio_id]).zats
    else
      @zats = Zat.all
   #    redirect_to action: 'index'
 end
 end

=begin
#zats#index action to account for whether the engineer/user is trying to 
access the index of all zats/recording_sessions (Zat.all) or 
just the index of all zats/recording_sessions 
by a certain artist (Artist.find(params[:artist_id]).zats). 
The conditional hinges on 
whether there's an :artist_id key in the params hash — in other words, 
whether the user navigated to /artists/:id/zats or simply /zats. 
=end



  def show
    index
    # binding.pry
    @zat = Zat.find(params[:id])
    #     redirect_to action: 'index'
    
  end

  def new
    @zat = Zat.new
    # params.require(:zat).permit(:appointment_date, :studio_id, :engineer_id, :artist_id)
    # if artist_id or not -- that
    # if nested_--tind artist build --what is associated
    index
  end

  def create
    # binding.pry
    @zat = Zat.new(zat_params)
    index
    # @zat = Zat.find(params[:id])
    if @zat.save
      # raise params.inspect
#      redirect_to action: 'index' # , notice: 'Recording Session created'
      redirect_to @zat # , notice: 'Recording Session created'
    else
      # @studios = Studio.all
      render action: 'new'
    end
  end

  def edit
    @zat = Zat.find(params[:id])
    index
  end

  #   def zat_param
  #     params.require(:zat).permit(:appointment_date, :studio_id, :engineer_id, :artist_id)
  #   end

  # def update
  # @zat = Zat.find(params[:id])
  # @zat.update(params.require(:zat).permit(:appointment_date, :studio, :engineer, :artist)
  # raise params.inspect
  # if @zat.update_attributes(zat_param)
  #    redirect_to action: 'show', id: @zat
  #  else

  #    @zats = Zat.all
  #    @engineers = Engineer.all
  #    @engineer = Engineer.find(params[:id])
  #    @studios = Studio.all
  #    @artists = Artist.all
  #    render action: 'edit'
  # end
  # end

  def update
    index
    @zat = Zat.find(params[:id])
    # raise params.inspect
    if @zat.update(params.require(:zat).permit(:appointment_date, :studio_id, :engineer_id, :artist_id))
      # binding.pry
      redirect_to zat_path(@zat)

    else
      render 'edit'
  end
  end

  #   def update
  #     @zat = Zat.find(params[:id])
  #     #@zat.update(params.require(:zat).permit(:appointment_date, :studio, :engineer, :artist)
  #     raise params.inspect
  #     if @zat.update_attributes(zat_param)
  #       redirect_to action: 'show', id: @zat
  #     else

  #       @zats = Zat.all
  #       @engineers = Engineer.all
  #       @engineer = Engineer.find(params[:id])
  #       @studios = Studio.all
  #       @artists = Artist.all
  #       render action: 'edit'
  #     end
  #   end

  def destroy
    Zat.find(params[:id]).destroy
    redirect_to action: 'index'
    #redirect_to zat_path
  end

  def show_studios
    @studio = Studio.find(params[:id])
  end
end

private

def zat_params
  params.require(:zat).permit(:appointment_date, :studio_id, :engineer_id, :artist_id)
end

app/helpers/zat_helper.rb
# frozen_string_literal: true

module ZatHelper
  #   def display_zat(engineer)
  #     engineer.zat.nil? ? link_to('Add Zat', edit_zat_path(engineer)) : link_to(engineer.zat_name, zat_path(engineer.zat))
  #   end
end

app/views/zats/_edit.html.erb
<!-- EDIT FORM -->
<%= form_for [@engineer,@zat] do |p| %>

<h2>Edit Recording Session</h2>
<h4>Use the dropdown menus below:</h4>
<h5>
    <label>Studio Location:</label><br>
    <%= select("zat", "studio_id", @studios.collect {|p| [ p.name, p.id] }, {prompt: 'Book Studio'}) %>
    <br>
    <br>
    <label>Appointment Date:</label><br>
    <%= select("zat", "appointment_date", @zats.collect {|p| [ p.appointment_date, p.id] }, {prompt: 'Select Date and Time'}) %>

    <br>
    <br>
    <label>Recording Engineer:</label><br>
    <%= select("zat", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>
    <br>
    <br>
    <label>Recording Artist:</label><br>
<%= select("zat", "artist_id", @artists.collect {|p| [ p.name, p.id] }, {prompt: 'Select Artist'}) %>
    <br>
    <br>
<input class="w3-input w3-padding-16" type="datetime-local" placeholder="Date and time" required name="date"
    value="2019-05-21T07:00"></p>
Appointment Date : <%= p.text_field :appointment_date %><br />
    <%= p.submit %>
    <% end %>
    </h4>
    <!-- END OF EDIT FORM -->


<%= link_to 'Delete Appointment', [@zat],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>

<%= link_to 'Show', @zat %> |
<%= link_to 'Recording Sessions', zats_path %>

app/views/zats/_edit_partial.html.erb
<%= form_for [@engineer,@zat] do |p| %>

<h2>Edit Session</h2>
<h4>Use the dropdown menus below:</h4>
<!-- Errors MESSAGING -->
<%if @zat.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@zat.errors.count, "error") %>
        prohibited this item from being saved:
        <% @zat.errors.full_messages.each do |msg| %>
    </h2>
    <ul style="list-style: none;">
            <li>
                <div class="alert alert-danger"><%= msg %></div>
        </li>
        <% end %>
        <% end %>
    </ul>
    
    
    <!-- EDIT FORM -->
    <h5>
    <label>Studio Location:</label><br>
    <%= select("zat", "studio_id", @studios.collect {|p| [ p.name, p.location, p.id] }, {prompt: 'Book Studio'}) %>
    <br>
    <br>
    <label>Session Date:</label><br>
    <%= select("zat", "appointment_date", @zats.collect {|p| [ p.appointment_date, p.id] }, {prompt: 'Select Date and Time'}) %>

    <br>
    <br>
    <label>Recording Engineer:</label><br>
    <%= select("zat", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>
    <br>
    <br>
    <label>Recording Artist:</label><br>
    <%= select("zat", "artist_id", @artists.collect {|p| [ p.name, p.id] }, {prompt: 'Select Artist'} ) %>
    <br>
    <br>

<input class="w3-input w3-padding-16" type="datetime-local" placeholder="Date and time" required name="date"
    value="2019-05-21T07:00"></p>
Session Date : <%= p.text_field(:appointment_date, {:class => 'form-control'}) %><br />
               <%= p.submit({:class => 'btn btn-primary'}) %>
                            <% end %>
<button>       <%= link_to "Delete", zat_path(@zat), 
                                     method: :delete, 
                                     data: {confirm: 'Are you sure you want to delete this session?'},
                                     :class => 'btn btn-default' %>
</button>
</h4>
<!-- END OF EDIT FORM -->

app/views/zats/_index_partial.html.erb
<!-- USED in views/zats/index -->

<!-- EDIT FORM -->
    <!-- DISPLAY Zat.ALL -->
    <section class="main">
    
        <%= link_to 'logout', destroy_engineer_session_path, method: :delete %>


        <% if @zats.blank? %>
        <h2>There are currently no recording sessions scheduled.</h2>
        <% else %>
        <h2>Scheduled Recording Sessions</h1>
            <br>
    
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Engineer</th>
                        <th>Artist</th>
                        <th>Studio</th>
                        <th>Location</th>
                        <th>Recording Session Date</th>
                        <th>Complete</th>
                        <th>Cancel</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
    
                <% Zat.incomplete.order('appointment_date ASC').each do |c| %>
<div class="well">
                <tbody>
                    <tr>
                        <td><%= link_to c.id, zat_path(c)%></td>
                        <td><%= link_to c.engineer.name.capitalize, engineer_path(c.engineer) %></a></td>
                        <td><%= link_to c.artist.name, artist_path(c.artist)%></td>
                        <td><%= link_to c.studio.name.capitalize, studio_path(c.studio)%></td>
                        <td><%= link_to c.studio.location.capitalize, studio_path(c.studio)%></td>
                        <td><%= link_to c.appointment_date.time.to_formatted_s(:rfc822), zat_path(c)%></td>
                        
                        <td><%= c.status %></td>
                        <td><%= link_to "Delete", c, method: :delete, data: { confirm: 'Are you sure you want to delete this recording session?' } %></td>

                    </tr>

                    <% end %>
                </tbody>
            </table>
            <%= link_to "LINK to ALL SESSIONS via (index_partial) ", zats_path(@zat), :class => 'btn btn-default' %>
</div>
            <p> <% end %> </p>

    <!-- END OF EDIT FORM -->

app/views/zats/_new_partial.html.erb
    <!-- NEW FORM -->
<%= form_for [@engineer,@zat], url: {action: "create"} do |p| %>

<h2>Create a New Session</h2>
<h4>Use the dropdown menus below:</h4>
<br>
        <%if @zat.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@zat.errors.count, "error") %>
                prohibited this item from being saved:
                <% @zat.errors.full_messages.each do |msg| %>
            </h2>
            <ul style="list-style: none;">
                <li><div class= "alert alert-danger"><%= msg %></div></li>
                <% end %>
            </ul>
            <%  end %>

    <h5>
         <%= select("zat", "studio_id", @studios.collect {|p| [ p.name, p.id] }, {prompt: 'Book Studio'}) %>
            <br>
            <br>
         <%= select("zat", "appointment_date", @zats.collect {|p| [ p.appointment_date] }, {prompt: 'Select Date and Time'}) %>

    <br>
    <br>
        <%= select("zat", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>
            <br>
            <br>
        <%= select("zat", "artist_id", @artists.collect {|p| [ p.name, p.id] }, {prompt: 'Select Artist'}) %>

    <br>
    <br>

    <%= p.submit({:class => 'btn btn-primary'}) %>
            <% end %>
</h4>
<!-- END OF NEW FORM -->

app/views/zats/edit.html.erb
    <body>
<%= render 'edit_partial', form: @zat %>
<br>
<!-- Last -->

app/views/zats/fedit.html.1.erb
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
    body {
        font-family: "Times New Roman", Georgia, Serif;
    }

    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        font-family: "Playfair Display";
        letter-spacing: 5px;
    }
</style>

<body>

    <!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
            <a href="#home" class="w3-bar-item w3-button">Book a recording session</a>
            <!-- Right-sided navbar links. Hide them on small screens -->
            <div class="w3-right w3-hide-small">
                <a href="#about" class="w3-bar-item w3-button">Studios</a>
                <a href="#menu" class="w3-bar-item w3-button">Artists</a>
                <a href="#contact" class="w3-bar-item w3-button">Engineers</a>
            </div>
        </div>
    </div>

<!-- Header -->

<h1 class="w3-xxlarge">View Studios</h1>
</div>
</header>

<body>

<br>



</ol>

<%= form_for :zat do |f| %>
Engineer: <%= f.text_field :engineer %><br />
Studio : <%= f.text_field :studio %><br />
Artist : <%= f.text_field :artist %><br />
Appointment Date : <%= f.text_field :appointment_date %><br />
<%= select("post", "studio_id", @studios.collect {|p| [ p.name, p.id ] }, {prompt: 'Studio...'}) %>
<%= f.submit %>
<% end %>

<br>
<br>
--------------------------------------------------
<table>
    <thead>
        <tr>
            <th>Engineer</th>
            <th>Artist</th>
            <th>Studio</th>
            <th>Recording Session Date</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <% @zats.each do |c| %>
    <tbody>
        <tr>
            <td><a href="/engineers/@engineer_id page/:id"><%= c.engineer.name.capitalize %></a></td>
            <td><a href="/artists/:artist_id"><%= c.artist.name.capitalize %></a></td>
            <td><a href="/studios/@studios_path"><%= c.studio.name.capitalize %></a></td>
            <td><a href="/zats/:id/edit"><%= c.appointment_date.time.to_formatted_s(:rfc822) %></a></td>
        </tr>
        <% end %>
    </tbody>
</table>
--------------------------------------------------


















---------------------------------------------------------------------------------------------------------------------------------------------
<br>
<br>

<%= form_for @zat , url: {action: "update"} do |f| %>
<%= f.label 'Recording Session Date' %><br>
<%= f.text_field :appointment_date %><br>


<%= f.label 'Recording Session Location' %><br>
<%= f.text_field :studio_id %><br>

<%= f.label 'Recording Session Engineer' %><br>
<%= f.text_field :engineer_id %><br>


<%= f.label 'Recording Session Artist' %><br>
<%= f.text_field :artist_id %><br>

<%= f.submit "Update" %>
<% end %>



------------------------------------------------
<div>
    
    <form class="edit_list" id="edit_list_1" action="/zats/:id" accept-charset="UTF-8" method="post">
        <input name="utf8" type="hidden" value="&#x2713;" />
        <input type="hidden" name="_method" value="patch" />
        <input type="hidden" name="authenticity_token"
            value="xvH5oMgncW/AZAVhIh5pXWtPoMYbQ/BjllTGLufOQVthBTwzBadiY4x1ExI8Um/HO5C/nu5wbGa0MrZq4xTiBg==" />
        <label for="appointment_date">Appointment Date</label>
        datetime_field_tag(name, value = nil, options = {})
        <input type="text" value="" name="zat[appointment_date]" id="appointment_date" />
        <input type="submit" name="commit" value="Update Appointment" />
    </form>

</div> 



<br>
<br>
<br>
<br>
<br>
---------------------------------------

<p class="w3-text-blue-grey w3-large"><b>Catering Service, 42nd Living St, 43043 New York, NY</b></p>
<p>You can also contact us by phone 00553123-2323 or email catering@catering.com, or you can send us a message here:</p>
<form action="/action_page.php" target="_blank">
    <%= select("post", "studio_id", @studios.collect {|p| [ p.name, p.id ] }, {prompt: 'Studio...'}) %>
    <p><input class="w3-input w3-padding-16" type="text" placeholder="Studio" required name="Name"></p>
    <p><input class="w3-input w3-padding-16" type="datetime-local" placeholder="Date and time" required name="date"
            value="2019-05-21T07:00"></p>
    <p><input class="w3-input w3-padding-16" type="artist" placeholder="Artist" required name="Artist"></p>
    <p><input class="w3-input w3-padding-16" type="text" placeholder="Engineer" required
            name="Message"></p>
    <p><button class="w3-button w3-light-grey w3-section" type="submit">Update</button></p>
</form>
</div>



------------------------------------------------------


<%= form_for :zat do |f| %>
<h2>Create a new recording session!</h2>
<br>
<h3>Please select from the dropdowns below to create your new recording session:</h3>



<%= select("post", "studio_id", @studios.collect {|p| [ p.name, p.id ] }, {prompt: 'Book a Studio...'}) %>

<br>
<br>
    <%= f.submit %>
    <% end %>
<br>
<br>














<!-- End page content -->
</div>

<!-- Footer -->
<footer class="w3-center w3-light-grey w3-padding-32">
    <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank"
            class="w3-hover-text-green">w3.css</a></p>
</footer>

</body>

</html>

app/views/zats/fedit.html.2.erb
<div>
    <h2> Edit Recording Session </h2>
    <%= form_for @zat , url: {action: "update"} do |f| %>
    <label>Engineer ID:</label><br>
    <%= f.text_field :engineer_id %><br>
    <label>Studio ID:</label><br>
    <%= f.text_field :studio_id %><br>
    <label>Artist ID:</label><br>
    <%= f.text_field :artist_id %><br>
    <input class="w3-input w3-padding-16" type="datetime-local" placeholder="Date and time" required name="date"
        value="2019-05-21T07:00"></p>
    Appointment Date : <%= f.text_field :appointment_date %><br />
    <%= f.submit %>
    <% end %>
    <br>

app/views/zats/findex.html.1.erb
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
    body {
        font-family: "Avenir Next", Georgia, Serif;
    }

    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        font-family: "Playfair Display";
        letter-spacing: 5px;
    }
</style>

<body>

    <!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
            <a href="#home" class="w3-bar-item w3-button">Book a recording session</a>
            <!-- Right-sided navbar links. Hide them on small screens -->
            <div class="w3-right w3-hide-small">
                <a href="#studios" class="w3-bar-item w3-button">Studios</a>
                <a href="#artists" class="w3-bar-item w3-button">Artists</a>
                <a href="#engineers" class="w3-bar-item w3-button">Engineers</a>
            </div>
        </div>
    </div>

    <!-- Header -->
    <header class="w3-display-container w3-content w3-wide" style="max-width:1600px;min-width:500px" id="home">
        <img class="w3-image" src="/w3images/hamburger.jpg" alt="Hamburger Catering" width="1600" height="800">
        <div class="w3-display-bottomleft w3-padding-large w3-opacity">
            <h1 class="w3-xxlarge">View Studios</h1>
        </div>
    </header>

    <body>

<% if @zats.blank? %>
<h2>There are currently no recording sessions scheduled.</h2>
<% else %>
<h2>Current recording sessions.</h2>
<br>
<p>
<ol id="zats">
    <% @zats.each do |c| %>
    <li> Studio: <%=c.studio.name.capitalize%> ***
         Engineer: <%=c.engineer.name.capitalize%> ***
         Artist: <%=c.artist.name.capitalize%> ***
         Date: <%= c.appointment_date %>
          <% if c.status == false %>
          Status: session scheduled
          <% else %>
          Status: session complete
            <% end %>
<br>
<br>
    </li>
    <% end %>
    <% end %>

</ol>
</p>



<p>

<ol>
<li>

        <% Zat.all.each do |c| %>
        <% if c.incomplete? %>
       <li> <% c.appointment_date %> </li>
        Status: session scheduled 
        <% else %>
       <li> Status: session complete </li>
        <% end %>
        <% end %>
</li>



</ol>


</p>

-----------------------------------------------------------------------------------------------------------------------------------------------------------

<%= form_for :zat do |f| %>
<h2>Create a new recording session!</h2>
<br>
<h3>Please select from the dropdowns below to create your new recording session:</h3>



<%= select("post", "studio_id", @studios.collect {|p| [ p.name, p.id ] }, {prompt: 'Book a Studio...'}) %>

<br>

<h5>
    <%= select("post", "zat_id", @zats.collect {|p| [ p.appointment_date ] }, {prompt: 'Select a date and time for your recording session:'}) %>
    
    <br>
    <br>
<%= select("post", "engineer_id", @engineers.collect {|p| [ p.name, p.id ] }, {prompt: 'Assign an Engineer...'}) %>

<br>
<br>

<%= select("post", "artist_id", @artists.collect {|p| [ p.name, p.id ] }, {prompt: 'Select an Artist...'}) %>

<br>
<br>
<%= f.submit %>
<% end %>
<br>
<br>


------------------------------------------------------------------------------------------
<h2>View Studios!</h2>



------------------------------------------------------------------------------------------
<h1>Recording Sessions</h1>

<table>
    <thead>
        <tr>
            <th>Engineer</th>
            <th>Artist</th>
            <th>Studio</th>
            <th>Recording Session Date</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <% @zats.each do |c| %>
    <tbody>
    <tr>
    <td><a href="/engineer/page/:id"><%= c.engineer.name.capitalize %></a></td>
    <td><a href="/artist/@artist_id"><%= c.artist.name.capitalize %></a></td>
    <td><a href="/studio/:id"></a><%= c.studio.name.capitalize %></a></td>
    <td><a href="/login"></a><%= c.appointment_date %></a></td>
    </tr>
        <% end %>
    </tbody>
</table>

<br>

app/views/zats/index.html.erb
<br>
<br>
<br>
<br>

<%= render 'index_partial', form: @zat %>

app/views/zats/new.html.erb
<%= render 'new_partial', form: @zat %>

app/views/zats/show.html.erb
<body>

<!-- RECORDING SESSION INFO -->
<div>
<h2> Scheduled Recording Session </h2>

Session ID: <%= @zat.id %>
<br>
Session Date: <%= @zat.appointment_date.time.to_formatted_s(:rfc822)  %>
<br>
Engineer: <%= @zat.engineer.name %>
<br>
Studio: <%= @zat.studio.name %>
<br>
Location: <%= @zat.studio.location %>
<br>
Artist: <%= @zat.artist.name %>
<br>
Recording Session Complete? <%= @zat.status %>
<br>
<%= DateTime.parse(@zat.appointment_date.to_s).strftime("%I:%M %p") %>
<br>
</div>

<div>
</body>

<button><%= link_to "Edit", edit_zat_path(@zat), :class => 'btn btn-default' %></button>
<button><%= link_to "Delete", zat_path(@zat), 
                        method: :delete, 
                        data: {confirm: 'Are you sure you want to delete this session?'} , :class => 'btn btn-default'%>
</button>

</div>